name: Automatisation des tests
on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test fonction add
        run: |
          cd build
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test fonction sub
        run: |
          cd build
          ./src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test fonction mul
        run: |
          cd build
          ./src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test fonction div
        run: |
          cd build
          ./src/calculator div 10 5

  Deployment:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div]
    steps:
      - name: Deployment
        run: echo "Deploying application..."
